# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InvoiceSchemaCompanyAddress(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, street: Object=None, city: Object=None, state: Object=None, zip_code: Object=None):  # noqa: E501
        """InvoiceSchemaCompanyAddress - a model defined in Swagger

        :param street: The street of this InvoiceSchemaCompanyAddress.  # noqa: E501
        :type street: Object
        :param city: The city of this InvoiceSchemaCompanyAddress.  # noqa: E501
        :type city: Object
        :param state: The state of this InvoiceSchemaCompanyAddress.  # noqa: E501
        :type state: Object
        :param zip_code: The zip_code of this InvoiceSchemaCompanyAddress.  # noqa: E501
        :type zip_code: Object
        """
        self.swagger_types = {
            'street': Object,
            'city': Object,
            'state': Object,
            'zip_code': Object
        }

        self.attribute_map = {
            'street': 'street',
            'city': 'city',
            'state': 'state',
            'zip_code': 'zip_code'
        }
        self._street = street
        self._city = city
        self._state = state
        self._zip_code = zip_code

    @classmethod
    def from_dict(cls, dikt) -> 'InvoiceSchemaCompanyAddress':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InvoiceSchema_company_address of this InvoiceSchemaCompanyAddress.  # noqa: E501
        :rtype: InvoiceSchemaCompanyAddress
        """
        return util.deserialize_model(dikt, cls)

    @property
    def street(self) -> Object:
        """Gets the street of this InvoiceSchemaCompanyAddress.


        :return: The street of this InvoiceSchemaCompanyAddress.
        :rtype: Object
        """
        return self._street

    @street.setter
    def street(self, street: Object):
        """Sets the street of this InvoiceSchemaCompanyAddress.


        :param street: The street of this InvoiceSchemaCompanyAddress.
        :type street: Object
        """

        self._street = street

    @property
    def city(self) -> Object:
        """Gets the city of this InvoiceSchemaCompanyAddress.


        :return: The city of this InvoiceSchemaCompanyAddress.
        :rtype: Object
        """
        return self._city

    @city.setter
    def city(self, city: Object):
        """Sets the city of this InvoiceSchemaCompanyAddress.


        :param city: The city of this InvoiceSchemaCompanyAddress.
        :type city: Object
        """

        self._city = city

    @property
    def state(self) -> Object:
        """Gets the state of this InvoiceSchemaCompanyAddress.


        :return: The state of this InvoiceSchemaCompanyAddress.
        :rtype: Object
        """
        return self._state

    @state.setter
    def state(self, state: Object):
        """Sets the state of this InvoiceSchemaCompanyAddress.


        :param state: The state of this InvoiceSchemaCompanyAddress.
        :type state: Object
        """

        self._state = state

    @property
    def zip_code(self) -> Object:
        """Gets the zip_code of this InvoiceSchemaCompanyAddress.


        :return: The zip_code of this InvoiceSchemaCompanyAddress.
        :rtype: Object
        """
        return self._zip_code

    @zip_code.setter
    def zip_code(self, zip_code: Object):
        """Sets the zip_code of this InvoiceSchemaCompanyAddress.


        :param zip_code: The zip_code of this InvoiceSchemaCompanyAddress.
        :type zip_code: Object
        """

        self._zip_code = zip_code
